#!/bin/sh
#$ -cwd
#$ -j y
#$ -V
#$ -l num_proc=1,mem_free=6G,h_rt=4:00:00
#$ -N "slda-giga-split"
export JAVA_HOME="/export/apps/java/bin/java"
export PATH="/export/apps/sbt-0.12.1/bin:$PATH"
export PATH="/export/apps/scala-2.9.2/bin:$PATH"
scala -J-Xmx4G -J-Xms4G -J-XX:+UseSerialGC -classpath 'lib/*:target/scala-2.9.2/slda_2.9.2-1.0.0.jar' wrangle.GigawordDatasetSplitter \
    0.8 \
    $HOME/slda/data/gigaword/nyt_eng \
    $HOME/slda/data/gigaword/nyt_eng.split
